version: 2.1
orbs:
  node: circleci/node@4.1.0

executors:
  releaser:
    docker:
      - image: circleci/node:latest-browsers
    resource_class: small

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - develop
jobs:
  build:
    executor: releaser
    steps:
      - checkout
      - node/install-packages:
          with-cache: false
      - run: echo 'Executing ci'
      - run: 'chmod +x scripts/release.sh'
      - run:
          name: 'Create release'
          command: GH_TOKEN=$GITHUB_TOKEN npm run release
